// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: leaf.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LeafRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain int64 `protobuf:"varint,1,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *LeafRequest) Reset() {
	*x = LeafRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafRequest) ProtoMessage() {}

func (x *LeafRequest) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafRequest.ProtoReflect.Descriptor instead.
func (*LeafRequest) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{0}
}

func (x *LeafRequest) GetDomain() int64 {
	if x != nil {
		return x.Domain
	}
	return 0
}

type LeafResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *LeafResponse) Reset() {
	*x = LeafResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_leaf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafResponse) ProtoMessage() {}

func (x *LeafResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafResponse.ProtoReflect.Descriptor instead.
func (*LeafResponse) Descriptor() ([]byte, []int) {
	return file_leaf_proto_rawDescGZIP(), []int{1}
}

func (x *LeafResponse) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_leaf_proto protoreflect.FileDescriptor

var file_leaf_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x25, 0x0a, 0x0b, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x26, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x66, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32,
	0x34, 0x0a, 0x04, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x2c, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x79, 0x72, 0x6f, 0x6e, 0x4c, 0x69, 0x61, 0x6e, 0x67, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x6e, 0x74, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_leaf_proto_rawDescOnce sync.Once
	file_leaf_proto_rawDescData = file_leaf_proto_rawDesc
)

func file_leaf_proto_rawDescGZIP() []byte {
	file_leaf_proto_rawDescOnce.Do(func() {
		file_leaf_proto_rawDescData = protoimpl.X.CompressGZIP(file_leaf_proto_rawDescData)
	})
	return file_leaf_proto_rawDescData
}

var file_leaf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_leaf_proto_goTypes = []interface{}{
	(*LeafRequest)(nil),  // 0: pb.LeafRequest
	(*LeafResponse)(nil), // 1: pb.LeafResponse
}
var file_leaf_proto_depIdxs = []int32{
	0, // 0: pb.Leaf.Query:input_type -> pb.LeafRequest
	1, // 1: pb.Leaf.Query:output_type -> pb.LeafResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_leaf_proto_init() }
func file_leaf_proto_init() {
	if File_leaf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_leaf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_leaf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_leaf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaf_proto_goTypes,
		DependencyIndexes: file_leaf_proto_depIdxs,
		MessageInfos:      file_leaf_proto_msgTypes,
	}.Build()
	File_leaf_proto = out.File
	file_leaf_proto_rawDesc = nil
	file_leaf_proto_goTypes = nil
	file_leaf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LeafClient is the client API for Leaf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeafClient interface {
	Query(ctx context.Context, in *LeafRequest, opts ...grpc.CallOption) (*LeafResponse, error)
}

type leafClient struct {
	cc grpc.ClientConnInterface
}

func NewLeafClient(cc grpc.ClientConnInterface) LeafClient {
	return &leafClient{cc}
}

func (c *leafClient) Query(ctx context.Context, in *LeafRequest, opts ...grpc.CallOption) (*LeafResponse, error) {
	out := new(LeafResponse)
	err := c.cc.Invoke(ctx, "/pb.Leaf/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeafServer is the server API for Leaf service.
type LeafServer interface {
	Query(context.Context, *LeafRequest) (*LeafResponse, error)
}

// UnimplementedLeafServer can be embedded to have forward compatible implementations.
type UnimplementedLeafServer struct {
}

func (*UnimplementedLeafServer) Query(context.Context, *LeafRequest) (*LeafResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterLeafServer(s *grpc.Server, srv LeafServer) {
	s.RegisterService(&_Leaf_serviceDesc, srv)
}

func _Leaf_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeafRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Leaf/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafServer).Query(ctx, req.(*LeafRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Leaf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Leaf",
	HandlerType: (*LeafServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Leaf_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaf.proto",
}
